name: dash_fanclub_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get_it: ^7.2.0
  chat_bubbles: ^1.2.0
  intl: ^0.17.0
  any_link_preview: ^2.0.8
  linkify: ^4.1.0
  flame: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dash.png
    - assets/images/shop/
    - assets/images/game/

flutter_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true